#!/bin/sh
./mvshader -fb 256 256 \
  -vshader ./shaders/vert/00.glsl \
  -fshader ./shaders/frag/01.glsl \
  -fshader ./shaders/frag/02.glsl \
  -fshader ./shaders/frag/03.glsl \
  -fshader ./shaders/frag/04.glsl \
  -fshader ./shaders/frag/05.glsl \
  -fshader ./shaders/frag/06.glsl \
  -fshader ./shaders/frag/07.glsl \
  -fshader ./shaders/frag/08.glsl \
  -fshader ./shaders/frag/09.glsl \
  -fshader ./shaders/frag/10.glsl \
  -fshader ./shaders/frag/11.glsl \
  -fshader ./shaders/frag/12.glsl \
  -fshader ./shaders/frag/13.glsl \
  -fshader ./shaders/frag/14.glsl \
  -fshader ./shaders/frag/15.glsl \
  -fshader ./shaders/frag/16.glsl \
  -fshader ./shaders/frag/17.glsl \
  -fshader ./shaders/frag/18.glsl \
  -fshader ./shaders/frag/19.glsl \
  -fshader ./shaders/frag/20.glsl \
  -fshader ./shaders/frag/21.glsl \
  -fshader ./shaders/frag/22.glsl \
  -fshader ./shaders/frag/23.glsl \
  -fshader ./shaders/frag/24.glsl \
  -fshader ./shaders/frag/25.glsl \
  -fshader ./shaders/frag/26.glsl \
  -fshader ./shaders/frag/27.glsl \
  -fshader ./shaders/frag/28.glsl \
  -fshader ./shaders/frag/29.glsl \
  -fshader ./shaders/frag/30.glsl \
  -fshader ./shaders/frag/31.glsl \
  -fshader ./shaders/frag/32.glsl \
  -fshader ./shaders/frag/33.glsl \
  -fshader ./shaders/frag/34.glsl
